(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const l of s)if(l.type==="childList")for(const u of l.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function r(s){const l={};return s.integrity&&(l.integrity=s.integrity),s.referrerPolicy&&(l.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?l.credentials="include":s.crossOrigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function a(s){if(s.ep)return;s.ep=!0;const l=r(s);fetch(s.href,l)}})();const E=document.querySelector(".burger"),c=document.querySelector(".burger-overlay"),q=document.querySelector(".burger-modal"),I=document.querySelector(".close-icon");E.addEventListener("click",()=>{c.classList.add("open")});I.addEventListener("click",()=>{c.classList.remove("open")});c.addEventListener("click",e=>{q.contains(e.target)||c.classList.remove("open")});const i=document.getElementById("name"),n=document.getElementById("email"),o=document.getElementById("comment"),m=document.querySelector(".form-btn"),p=document.querySelector(".form-wrapper");let f=!1,y=!1,L=!1;const d=()=>{const e=i.value.trim()!==""&&n.value.trim()!==""&&o.value.trim()!=="";m.disabled=!e,m.classList.toggle("disabled",!e)},g=()=>{const e=document.getElementById("errName"),t=i.value.trim();f&&t===""?(i.classList.add("invalid"),e.style.display="block"):(i.classList.remove("invalid"),i.classList.add("valid"),e.style.display="none"),d()},h=()=>{const e=document.getElementById("errEmail"),t=n.value.trim();y&&(t===""||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(t))?(n.classList.add("invalid"),n.classList.remove("valid"),e.style.display="block"):(n.classList.remove("invalid"),n.classList.add("valid"),e.style.display="none"),d()},b=()=>{const e=document.getElementById("errComment"),t=o.value;L&&t===""?(o.classList.add("invalid"),e.style.display="block"):(o.classList.remove("invalid"),o.classList.add("valid"),e.style.display="none"),d()};i.addEventListener("blur",()=>{f=!0,g()});i.addEventListener("input",g);n.addEventListener("blur",()=>{y=!0,h()});n.addEventListener("input",h);o.addEventListener("blur",()=>{L=!0,b()});o.addEventListener("input",b);p.addEventListener("submit",e=>{e.preventDefault(),d(),m.disabled?(i.classList.add("invalid"),n.classList.add("invalid"),o.classList.add("invalid")):(p.reset(),i.classList.remove("valid"),n.classList.remove("valid"),o.classList.remove("valid"))});const v=document.querySelector(".faq-list");for(let e=1;e<=5;e++){const t=document.createElement("li");t.classList.add("faq-list-item"),t.innerHTML=`
        <div class="question-wrapper">
          <h4 class="question">How do I change my details?</h4>
          <svg class="plus-icon" width="32" height="32">
            <use href="../img/sprite.svg#icon-plus" />
          </svg>
        </div>
        <p class="answer">
          We provide only the best trading software. The trading terminal
          MetaTrader4 is the most popular and convenient platform for access to
          global exchanges. You can work anywhere. All you need is the Internet
          because the necessary trading tools are already collected in one place
          and are available in a couple of clicks. Use only the best and develop
          with us!
        </p>`,v.appendChild(t)}const w=e=>{const t=e.target.closest(".question-wrapper");if(!t)return;const r=t.closest(".faq-list-item"),a=t.nextElementSibling;v.querySelectorAll(".faq-list-item").forEach(l=>{l!==r&&(l.classList.remove("open"),l.querySelector(".answer").classList.remove("open"))}),a.classList.toggle("open"),r.classList.toggle("open")};v.addEventListener("click",w);
//# sourceMappingURL=index.js.map
